# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: get-pom-version
      id: pom-version
      uses: CptMokoena/maven-get-version-action@master
  
    - name: Build the docker image
      run: docker build -t akessil/question-app:${{steps.pom-version.outputs.version}} .
      
    - name: login to docker hub
      run: docker login --username akessil --password ${{secrets.docker_token}}
      
    - name: push the new docker image to docker hub
      run: docker push akessil/question-app:${{steps.pom-version.outputs.version}}
    
